server:
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.236.37.1:3306/books_management?useSSL=false&serverTimezone=UTC
    username: parter
    password: COMEONboy123.

mybatis-plus:
  type-aliases-package: com.seven.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    global-config:
      db-config:
        id-type: auto

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

books:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

